mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://10.245.142.204:3306/tws?useSSL=false&serverTimezone=UTC
    username: tws
    password: root


